[package]
name = "tihdy"
version = "0.1.0"
authors = ["Edvard Th√∂rnros <edvard.thornros@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
