[package]
name = "sylt-parser"
version = "0.1.0"
edition = "2018"

[lib]
path = "src/parser.rs"

[dependencies]
sylt-common = { version = "0.1.0", path = "../sylt-common" }
sylt-tokenizer = { version = "0.1.0", path = "../sylt-tokenizer" }
sylt_macro = { version = "0.1.0", path = "../sylt_macro" }
